### ISSUE TITLE
Precision error

### ISSUE THREAD

**Issue by RedCuckoo** [JnyJny/Geometry#1]
I know, this is an old project, but I was using this library for my university project and getting an error in the end, because of the points checked without precisionat the end of the method _intersection_. You commented that it's not possible error, but I am getting it most of the time. In the class _Line_.

https://github.com/JnyJny/Geometry/blob/master/Geometry/line.py

**Comment by JnyJny** [comment]
Sorry for the late response, a winter storm knocked out power and water for a couple of days. 

I agree, this library is pretty old and hasn't seen a lot of testing. Could you be more specific about the inputs to `Line.intersection` that are causing problems?

**Comment by RedCuckoo** [comment]
No problem, I hope it's back to normal over there!

Providing minimal reproducible code (please notice, that I passed 1.1 as a parameter of one point to the first line):
<pre><code>from Geometry import Line
from Geometry import Point


def main():
    l1 = Line(Point(1.1, 1), Point(4, 4))
    l2 = Line(Point(3, 1), Point(1, 3))
    intersection_points = l1.doesIntersect(l2)
    print(intersection_points)
    print(l1.intersection(l2))


main()
</code></pre>

With the following output:
<pre><code>LAPTOP\lib_reproducing\venv\Scripts\python.exe Laptop/lib_reproducing/main.py
True
Traceback (most recent call last):
  File "LAPTOP\lib_reproducing\main.py", line 13, in <module>
    main()
  File "LAPTOP\lib_reproducing\main.py", line 10, in main
    print(l1.intersection(l2))
  File "LAPTOP\lib_reproducing\venv\lib\site-packages\Geometry\line.py", line 384, in intersection
    raise Parallel(msg.format(p=p,a=self,b=other))
NameError: name 'Parallel' is not defined

Process finished with exit code 1</pre></code>
Please notice, that the check for the existence of the intersection point passed successfully.

It seems, that it can't work properly when an intersection point is a number with floating point. Looks like it fails to complete this check.
<pre><code>        if p in self and p in other:
            return p</code></pre>

**Comment by JnyJny** [comment]
Yup, I agree that floating point epsilons are probably gumming up the works here. Looking at this code just reminds me how much I need to go back and re-write a lot of it :)

Thank you for the test case and I'll see what I can figure out.
